# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [13]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [14]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [16]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [28]:
arrr = np.arange(20, 35, 2)
print(arr)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.concatenate((a, b))
print(res)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [29]:
import pandas as pd


In [32]:
dics = {"key1": [1, 2, 3], "key2": [4, 5, 6]}

df = pd.DataFrame(dics)

print(df)

   key1  key2
0     1     4
1     2     5
2     3     6


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [34]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame(lists)

print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
